/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigFieldRenderer: typeof import('./../pages/config/components/ConfigFieldRenderer.vue')['default']
    ConfigGroupRenderer: typeof import('./../pages/config/components/ConfigGroupRenderer.vue')['default']
    FrontMatterForm: typeof import('./../components/FrontMatterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
}
