name: Release

on:
  push:
    tags:
      - "v*" # e.g. v3.0.8

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Remove specific lines from README.md
        run: sed -i '3,7d' README.md

      - name: Install VSCE + OVSX
        run: npm install -g @vscode/vsce ovsx

      - name: Package the extension
        run: vsce package --no-dependencies
        # produces vscode-hexo-github-<version>.vsix

      - name: Set Release Name
        id: set_release_name
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          files: vscode-hexo-github-*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VS Code Marketplace
        if: success()
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --packagePath vscode-hexo-github-*.vsix

      - name: Publish to Open VSX (optional)
        if: success() && env.OVSX_PAT != ''
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: ovsx publish vscode-hexo-github-*.vsix
